export const ActionTypes = {
	SET_STOCK_LIST: 'SET_STOCK_LIST',
	SET_STOCK_NAME_LIST: 'SET_STOCK_NAME_LIST',
	SET_FILTERED_STOCK: 'SET_FILTERED_STOCK',
	SET_BALANCE: 'SET_BALANCE',
	SET_PORTFOLIO: 'SET_PORTFOLIO',
	SET_CURRENT_STOCK: 'SET_CURRENT_STOCK',
	SET_LOADER: 'SET_LOADER',
	SET_DATE_FILTER: 'SET_DATE_FILTER',
	SET_STOCK_ON_DATE: 'SET_STOCK_ON_DATE',
	SET_STOCK_FILTER: 'SET_STOCK_FILTER',
};
